##########################################
# BUILD STAGE (Alpine)
##########################################
FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY . .

RUN go build -o calculator .

##########################################
# RUNTIME STAGE (Alpine)
##########################################
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/calculator .

ENTRYPOINT ["./calculator"]
